### ISSUE TITLE
Collections with slash in name cannot be deleted

### ISSUE THREAD

**Issue by honzasterba** [typesense/typesense-ruby#28]
## Description

When you create a collection with / in the name, its impossible to work with such collection and eventually delete it

## Steps to reproduce

create collection with / in the name
try deleting it
or importing some data into it

## Expected Behavior

collection gets deleted
(internally the client should escape slash (/) with %2F whenever collection name is put in the URL path

## Actual Behavior

404 is retuned

## Metadata

**Typesense Version**: any

**OS**: any

**Comment by JoeGonzalez0886** [comment]
problem across all typsense libs not just ruby.
